import 'package:flutter/foundation.dart';

abstract class AppImages {
  const AppImages();
  static const releasePath = kDebugMode ? '' : 'assets/';

  static const String iAwful                = "${releasePath}images/i_awful.svg";
  static const String iBad                  = "${releasePath}images/i_bad.svg";
  static const String iClose                = "${releasePath}images/i_close.svg";
  static const String iClubs                = "${releasePath}images/i_clubs.svg";
  static const String iDetailBackground     = "${releasePath}images/i_detail_background.png";
  static const String iDislike              = "${releasePath}images/i_dislike.svg";
  static const String iEdit                 = "${releasePath}images/i_edit.svg";
  static const String iExcellent            = "${releasePath}images/i_excellent.svg";
  static const String iFacilities           = "${releasePath}images/i_facilities.svg";
  static const String iFlag                 = "${releasePath}images/i_flag.svg";
  static const String iFood                 = "${releasePath}images/i_food.svg";
  static const String iGood                 = "${releasePath}images/i_good.svg";
  static const String iHeart                = "${releasePath}images/i_heart.svg";
  static const String iHidePassword         = "${releasePath}images/i_hide_password.svg";
  static const String iHomeBackground       = "${releasePath}images/i_home_background.png";
  static const String iHomeBody1            = "${releasePath}images/i_home_body_1.png";
  static const String iHomeBody2            = "${releasePath}images/i_home_body_2.png";
  static const String iHomeBody3            = "${releasePath}images/i_home_body_3.png";
  static const String iHomeHeaderBackground = "${releasePath}images/i_home_header_background.png";
  static const String iHomeLogo             = "${releasePath}images/i_home_logo.png";
  static const String iInternet             = "${releasePath}images/i_internet.svg";
  static const String iLike                 = "${releasePath}images/i_like.svg";
  static const String iLocation             = "${releasePath}images/i_location.svg";
  static const String iLogoPrimary          = "${releasePath}images/i_logo_primary.svg";
  static const String iLogoWhite            = "${releasePath}images/i_logo_white.svg";
  static const String iMedium               = "${releasePath}images/i_medium.svg";
  static const String iMenu                 = "${releasePath}images/i_menu.svg";
  static const String iOpportunities        = "${releasePath}images/i_opportunities.svg";
  static const String iPaint                = "${releasePath}images/i_paint.svg";
  static const String iProtect              = "${releasePath}images/i_protect.svg";
  static const String iStudentCap           = "${releasePath}images/i_student_cap.svg";
  static const String iHomeLike             = "${releasePath}images/i_home_like_new.png";
  static const String iHomeManager          = "${releasePath}images/i_home_manager_new.png";
  static const String iHomePrivate          = "${releasePath}images/i_home_private_new.png";
  static const String iSearch               = "${releasePath}images/i_search.svg";
  static const String iGoogleLogo           = "${releasePath}images/i_google_logo.png";
  static const String iBack                 = "${releasePath}images/i_back.svg";
  static const String iCompete              = "${releasePath}images/i_compete.svg";
  static const String iReputation           = "${releasePath}images/i_reputation.svg";
  static const String iSheetClose           = "${releasePath}images/i_sheet_close.svg";
  static const String iWarning           = "${releasePath}images/i_warning.svg";
  static const String iHandHeart           = "${releasePath}images/i_hand_heart.svg";
  static const String iSuccessBg           = "${releasePath}images/i_success_bg.svg";
  static const String iFacebook           = "${releasePath}images/i_facebook.svg";
  static const String iInstagram           = "${releasePath}images/i_instagram.svg";
}
